# Compose fileのバージョンを指定する。
# 最新バージョンを使用する場合は、指定不要となる。
# version: '3.9'

services:

  ################################
  # web
  ################################
  web:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    image: nginx-alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/src:/usr/share/nginx/html
    networks:
      - web

networks:
  web:
    driver: bridge
